### ISSUE TITLE
[Question] No server download link in CurseForge (v2.4.1)?

### ISSUE THREAD

**Issue by DragonRaiderII** [mahjerion/Craft-to-Exile-Dissonance-Server#2]
**Question:**
- Are the server files for v2.4.1 available on CurseForge, or is it still in development?

**Additional Info:**
- I was looking through the CurseForge project and noticed that v2.4.1 didn't have an associated server file available.
- My friends and I have been playing this pack on a private server, and we were looking to update.
- Any information on the server files status would be greatly appreciated.

**Comment by mahjerion** [comment]
hey thanks for asking, currently there's some sort of CurseForge bug with the 2.4.1 server pack. I've e-mailed support so hopefully it gets resolved. will keep this issue open so others can see my response

**Comment by mahjerion** [comment]
nvm this is on my server issues not client issues tracker hehe, closing
